### ISSUE TITLE
Fatal Error Call

### ISSUE THREAD

**Issue by djmaxw3ll** [digital-dj-tools/dj-data-converter#33]
![image](https://user-images.githubusercontent.com/19673395/88020590-ee44c680-cb23-11ea-806e-f536b5baaa0e.png)

**Comment by alzadude** [comment]
Thanks for reporting this @djmaxw3ll 🙂

What is the size of the collection you're trying to convert, how many tracks?

Thanks

**Comment by djmaxw3ll** [comment]
Hi Alex, roughly 25,000

Regards

Peter Maxwell
07399 829573
0fad0940@opayq.com

**Comment by alzadude** [comment]
Hi @djmaxw3ll,

Some good news, I've now got a working build that should allow larger collections to be processed more efficiently without running out of memory 🙂

Here's a very informal performance comparison between the existing NodeJS build and the new experimental GraalVM build...
```
alex@localhost:/mnt/d/Projects/dj-data-converter$ time nodejs ./out/cli.js -w /mnt/c/Users/alex/Documents/Native\ Instruments/Traktor\ 2.11.3/collection.nml

Conversion completed

real    3m48.585s
user    2m1.602s
sys     0m6.789s

alex@localhost:/mnt/d/Projects/dj-data-converter$ time ./target/dj-data-converter -w /mnt/c/Users/alex/Documents/Native\ Instruments/Traktor\ 2.11.3/collection.nml

Conversion completed

real    1m20.615s
user    0m38.234s
sys     0m4.089s
```
Looks promising, although this is just execution time of course and not memory usage. However, I'm hoping that memory usage will be lower on GraalVM, because the Clojure/Java implementation of data.xml parsing is much more efficient than the ClojureScript/NodeJS implementation, and will therefore allow larger files to be processed without running out of memory.

The next step is to modify the Azure Devops build to produce Windows and/or Mac GraalVM images for testing.

Regarding Windows and/or Mac, from the screenshot above it looks like you're on Windows, is that correct @djmaxw3ll?

Thanks!

**Comment by alzadude** [comment]
Hi @djmaxw3ll,

I've got a Windows build for you to test with, see attached...

Please can you download, run it on your Traktor collection and let me know the result?

Thanks! 🙂

[dj-data-converter-win.zip](https://github.com/digital-dj-tools/dj-data-converter/files/5374282/dj-data-converter-win.zip)
