### ISSUE TITLE
Error converting from traktor to rekordbox

### ISSUE THREAD

**Issue by danthp4** [digital-dj-tools/dj-data-converter#40]
![image](https://user-images.githubusercontent.com/47222489/99394328-9c942900-28d6-11eb-95ba-56193909b8bc.png)

Error trying to convert traktor to rekordbox xml, error file in the zip for you.

[error-report.zip](https://github.com/digital-dj-tools/dj-data-converter/files/5553630/error-report.zip)

**Comment by alzadude** [comment]
Hi @danthp4,

I recently released a new version of the converter which has a fix for #42, and because I suspect this is actually same issue, please give it a try and let me know if it works on your collections:

https://github.com/digital-dj-tools/dj-data-converter/releases/tag/0.5.1

Once I've got confirmation that the fix is working, I can mark this issue as a duplicate of #42 and close it.

Thanks 🙏🙂

**Comment by danthp4** [comment]
Yes, it works now!
